spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/course
    driver-class-name: org.mariadb.jdbc.Driver
    username: zero
    password: base

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/

  mail:
    host: smtp.gmail.com
    port: 587
    username: malslapq@gmail.com
    password: rkyaetpapscymzlq
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB